In [35]:
import numpy as np






seed = [[0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0],
        [0,0,0,1,1,0,0,0],
        [0,0,0,0,1,0,0,0],
        [0,0,0,0,1,0,0,0],
        [0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0]]

def spread(a, t):
    nVisualize = np.zeros((len(a),len(a)))
    #to look at the positions of the surrounding numbers of the object in question
    nPos = np.zeros((len(a),len(a)))
    
    #list of cells to be deleted
    deleteListF = []
    deleteListG = []
    
    #place hoders for i and j
    f = 0
    g = 0
    
    print "Stage 0:"
    for i in range(len(a)):
        print a[i]
            
    for z in range(t):
        


        n = 0

        for i in range(len(a)-2):
            for j in range(len(a)-2):
                n = 0

                #this shifts the 4x4 into the middle of the 6x6 grid
                f=i
                f+=1

                g=j
                g+=1

                #reset
                #test
                if a[f-1][g-1] == 1:
                    n += 1
                    nPos[f-1][g-1] = 8
                else:
                    nPos[f-1][g-1] = 0


                if a[f-1][g] == 1:
                    n += 1
                    nPos[f-1][g] = 8
                else:
                    nPos[f-1][g] = 0


                if a[f-1][g+1] == 1:
                    n += 1
                    nPos[f-1][g+1] = 8
                else:
                    nPos[f-1][g+1] = 0


                if a[f][g-1] == 1:
                    n += 1
                    nPos[f][g-1] = 8
                else:
                    nPos[f][g-1] = 0


                if a[f][g+1] == 1:
                    n += 1
                    nPos[f][g+1] = 8
                else:
                    nPos[f][g+1] = 0


                if a[f+1][g-1] == 1:
                    n += 1
                    nPos[f+1][g-1] = 8
                else:
                    nPos[f+1][g-1] = 0


                if a[f+1][g] == 1:
                    n += 1
                    nPos[f+1][g] = 8
                else:
                    nPos[f+1][g] = 0


                if a[f+1][g+1] == 1:
                    n += 1
                    nPos[f+1][g+1] = 8
                else:
                    nPos[f+1][g+1] = 0


                nVisualize[i][j] = n

                #print nPos
                nPos[f][g] = 4
                print "----------"
                print "location: (%d,%d)" % (f,g)
                for l in range(len(a)):
                    print nPos[l]
                nPos[f][g] = 0

                #destroy/create cell
                
                if ((a[f][g] == 1) and (n >= 2)) and (n <= 3):
                    a[f][g] = 1
                    
                    #maintain cell

                if (a[f][g] == 0) and (n == 3):
                    a[f][g] = 2
                    print "created cell: (%s,%s)" % (str(f),str(g))
                    #create cell
                if ((n > 3) or (n < 2)) and (a[f][g] == 1):
                    #deleting needs to happen outside of for loop
                    #we will store x val in one list and y val in the other and delete later
                    deleteListF.append(f)
                    deleteListG.append(g)
                    print "----- deleted cell (%d,%d) because:" % (f,g)
                    if n>3:
                        print "----- n > 3"
                        print "----- n = "+ str(n)
                    elif n<2:
                        print "----- n < 2"
                        print "----- n = "+ str(n)

                    #delete cell



        for i in range(len(a)-2):
            for j in range(len(a)-2):
                f=i
                f+=1

                g=j
                g+=1

                if a[f][g] == 2:
                    a[f][g] = 1


        for i in range(len(deleteListF)):

            j = deleteListF[i]
            k = deleteListG[i]
            a[j][k] = 0


        """print "Stage N:"
        for i in range(len(a)):
            print nVisualize[i]"""
        
        score = 0
        
        print "Stage %s:" % z
        for i in range(len(a)):
            print a[i]
            
            score += sum(a[i])
    return score
spread(seed, 3)




Stage 0:
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 1, 0, 0, 0]
[0, 0, 0, 0, 1, 0, 0, 0]
[0, 0, 0, 0, 1, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
----------
location: (1,1)
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 4. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
----------
location: (1,2)
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 4. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
----------
location: (1,3)
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 4. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
----------
location: (1,4)
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 4. 0. 0. 0.]
[0. 0. 

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 8. 8. 0. 0. 0.]
[0. 0. 0. 0. 8. 8. 0. 0.]
[0. 0. 0. 4. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
----------
location: (5,4)
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 8. 8. 0. 0. 0.]
[0. 0. 0. 0. 8. 8. 0. 0.]
[0. 0. 0. 0. 4. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
----------
location: (5,5)
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 8. 8. 0. 0. 0.]
[0. 0. 0. 0. 8. 8. 0. 0.]
[0. 0. 0. 0. 0. 4. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
----------
location: (5,6)
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 8. 8. 0. 0. 0.]
[0. 0. 0. 0. 8. 8. 0. 0.]
[0. 0. 0. 0. 0. 0. 4. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
----------
location: (6,1)
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0

5